name: Deploy Workflow

on:
  push:
    branches:
      - 'main'
     
jobs:

  deploy-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: heroku_api_key: ${{secrets.CHAVE_HEROKU}}
          heroku_app_name: "webacademy-alisson"
          heroku_email: "alissonM.l@hotmail.com"
