name: CI Workflow Main
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Maven Compile/Test
        run: mvn --activate-profiles prod test
        
# job2 essa linha está dando erro:
  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Maven Compile/Test/Package
        run: mvn --activate-profiles prod package -DskipTests
      
